version: '3'

services:
  webserver:
    image: typo3.webserver
    build: ./base
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - fileadmin:/var/www/html/web/fileadmin
      - l10n:/var/www/html/web/typo3conf/l10n
      - typo3temp:/var/www/html/web/typo3temp
      - uploads:/var/www/html/web/uploads
    networks:
      - db
    depends_on:
      - db
    environment:
      - TYPO3_CONTEXT=${TYPO3_CONTEXT}
      - APACHE_DOMAIN=${APACHE_DOMAIN}
      - APACHE_DOCUMENT_ROOT=/var/www/html/web

  db:
    image: mariadb:10.3
    command: --character-set-server=utf8 --collation-server=utf8_unicode_ci
    ports:
      - "3306:3306"
    volumes:
      - path=/var/lib/mysql
    networks:
      - db
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}

volumes:
  fileadmin:
  l10n:
  typo3temp:
  uploads:

networks:
  db:
